# Site settings
title: NLP小学生
#motto: Your motto
email: wuhaixu1993@163.com
description: > # this means to ignore newlines until "baseurl:"
  自然语言处理和深度学习
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wuhaixutab.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wuhaixutab

# Build settings
markdown: kramdown
